vich_uploader:
    metadata:
        type: attribute
    db_driver: orm
    mappings:
        avatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        post:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        story:
            uri_prefix: /images/story
            upload_destination: '%kernel.project_dir%/public/images/story'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
